// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Aller sur un projet et ajouter un issue en tant que dev', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Aller sur un projet et ajouter un issue en tant que dev', async function() {
    await driver.get("http://localhost:4200/login")
    await driver.manage().window().setRect(1347, 748)
    await driver.findElement(By.css(".ng-tns-c5-0 .mat-form-field-infix")).click()
    await driver.findElement(By.id("mat-input-0")).sendKeys("fred@gmail.com")
    await driver.findElement(By.id("mat-input-1")).click()
    await driver.findElement(By.id("mat-input-1")).sendKeys("repasser")
    await driver.findElement(By.id("mat-input-1")).sendKeys(Key.ENTER)
    {
      const element = await driver.findElement(By.css(".nav-menu .mat-button-wrapper"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.id("collab"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".mat-row:nth-child(1) #view .mat-icon"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".mat-row:nth-child(1) #view .mat-icon")).click()
    {
      const element = await driver.findElement(By.css(".button-add:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".cdk-focused")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.id("mat-input-4")).click()
    await driver.findElement(By.id("mat-input-4")).sendKeys("En tant que testeur je veux tester mon appli")
    await driver.findElement(By.css("#mat-select-5 .mat-select-value")).click()
    await driver.findElement(By.css("#mat-option-14 > .mat-option-text")).click()
    await driver.findElement(By.id("mat-input-5")).click()
    await driver.findElement(By.id("mat-input-5")).sendKeys("5")
    await driver.findElement(By.css(".mr-1 > .mat-button-wrapper")).click()
    await driver.executeScript("window.scrollTo(0,700)")
  })
})
