// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Aller sur le suvi et Finir une tâche', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Aller sur le suvi et Finir une tâche', async function() {
    // Test name: Aller sur le suvi et Finir une tâche
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:4200/sprint/5deee0a4ff8d4749888b2b74 |  | 
    await driver.get("http://localhost:4200/sprint/5deee0a4ff8d4749888b2b74")
    // 2 | setWindowSize | 1347x748 |  | 
    await driver.manage().window().setRect(1347, 748)
    // 3 | mouseOver | css=.button-right |  | 
    {
      const element = await driver.findElement(By.css(".button-right"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 4 | mouseOut | css=.button-right |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 5 | click | css=.button-right .mat-icon |  | 
    await driver.findElement(By.css(".button-right .mat-icon")).click()
    // 6 | mouseDownAt | css=#cours .mat-expansion-panel-header-description | 67.21875,5.15625 | 
    {
      const element = await driver.findElement(By.css("#cours .mat-expansion-panel-header-description"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 7 | mouseMoveAt | css=#cours .mat-expansion-panel-header-description | 67.21875,5.15625 | 
    {
      const element = await driver.findElement(By.css("#cours .mat-expansion-panel-header-description"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 8 | mouseUpAt | css=#cours .mat-expansion-panel-header-description | 67.21875,5.15625 | 
    {
      const element = await driver.findElement(By.css("#cours .mat-expansion-panel-header-description"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 9 | mouseDownAt | id=finish | 140.890625,56 | 
    {
      const element = await driver.findElement(By.id("finish"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 10 | mouseMoveAt | id=finish | 140.890625,56 | 
    {
      const element = await driver.findElement(By.id("finish"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 11 | mouseUpAt | id=finish | 140.890625,56 | 
    {
      const element = await driver.findElement(By.id("finish"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 12 | mouseDownAt | css=#finish .mat-expansion-panel-header-description | 47.21875,17 | 
    {
      const element = await driver.findElement(By.css("#finish .mat-expansion-panel-header-description"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 13 | mouseMoveAt | css=#finish .mat-expansion-panel-header-description | 47.21875,17 | 
    {
      const element = await driver.findElement(By.css("#finish .mat-expansion-panel-header-description"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 14 | mouseUpAt | css=#finish .mat-expansion-panel-header-description | 47.21875,17 | 
    {
      const element = await driver.findElement(By.css("#finish .mat-expansion-panel-header-description"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 15 | click | css=.cdk-focused > .mat-button-wrapper |  | 
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
    // 16 | mouseOver | css=.mat-raised-button:nth-child(1) > .mat-button-wrapper |  | 
    {
      const element = await driver.findElement(By.css(".mat-raised-button:nth-child(1) > .mat-button-wrapper"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 17 | mouseDownAt | css=.cdk-focused > .mat-button-wrapper | 30.734375,4 | 
    {
      const element = await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 18 | mouseMoveAt | css=.cdk-focused > .mat-button-wrapper | 30.734375,4 | 
    {
      const element = await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 19 | mouseUpAt | css=.cdk-focused > .mat-button-wrapper | 30.734375,4 | 
    {
      const element = await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 20 | click | css=.cdk-focused > .mat-button-wrapper |  | 
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
    // 21 | mouseDownAt | css=.ng-tns-c19-65:nth-child(2) | 9.890625,11 | 
    {
      const element = await driver.findElement(By.css(".ng-tns-c19-65:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 22 | mouseMoveAt | css=.ng-tns-c19-65:nth-child(2) | 9.890625,11 | 
    {
      const element = await driver.findElement(By.css(".ng-tns-c19-65:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 23 | mouseUpAt | css=.ng-tns-c19-65:nth-child(2) | 9.890625,11 | 
    {
      const element = await driver.findElement(By.css(".ng-tns-c19-65:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 24 | click | css=.ng-tns-c19-65:nth-child(2) |  | 
    await driver.findElement(By.css(".ng-tns-c19-65:nth-child(2)")).click()
    // 25 | runScript | window.scrollTo(0,300) |  | 
    await driver.executeScript("window.scrollTo(0,300)")
    // 26 | mouseOver | css=.mat-expansion-panel-header-description > .mat-primary |  | 
    {
      const element = await driver.findElement(By.css(".mat-expansion-panel-header-description > .mat-primary"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 27 | mouseOut | css=.mat-expansion-panel-header-description > .mat-primary |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 28 | mouseDownAt | css=#cours .mat-expansion-panel-header-description | 51.21875,17.15625 | 
    {
      const element = await driver.findElement(By.css("#cours .mat-expansion-panel-header-description"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 29 | mouseMoveAt | css=#cours .mat-expansion-panel-header-description | 51.21875,17.15625 | 
    {
      const element = await driver.findElement(By.css("#cours .mat-expansion-panel-header-description"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 30 | mouseUpAt | css=#cours .mat-expansion-panel-header-description | 51.21875,17.15625 | 
    {
      const element = await driver.findElement(By.css("#cours .mat-expansion-panel-header-description"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 31 | mouseOver | css=.button-right |  | 
    {
      const element = await driver.findElement(By.css(".button-right"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 32 | mouseOut | css=.button-right |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 33 | mouseOver | css=.mat-basic |  | 
    {
      const element = await driver.findElement(By.css(".mat-basic"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 34 | mouseOut | css=.mat-basic |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 35 | click | css=.mat-basic .mat-icon |  | 
    await driver.findElement(By.css(".mat-basic .mat-icon")).click()
    // 36 | mouseDownAt | css=.cdk-overlay-backdrop | 1110,280 | 
    {
      const element = await driver.findElement(By.css(".cdk-overlay-backdrop"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 37 | mouseMoveAt | css=.cdk-overlay-backdrop | 1110,280 | 
    {
      const element = await driver.findElement(By.css(".cdk-overlay-backdrop"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 38 | mouseUpAt | css=.cdk-overlay-backdrop | 1110,280 | 
    {
      const element = await driver.findElement(By.css(".cdk-overlay-backdrop"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 39 | mouseOver | css=.mat-basic |  | 
    {
      const element = await driver.findElement(By.css(".mat-basic"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 40 | mouseOut | css=.mat-basic |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 41 | click | css=.cdk-overlay-backdrop |  | 
    await driver.findElement(By.css(".cdk-overlay-backdrop")).click()
  })
})
