// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Placer un Issue du backlog vers un sprint et du sprint vers le backlog', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Placer un Issue du backlog vers un sprint et du sprint vers le backlog', async function() {
    await driver.get("http://localhost:4200/project/5deee0a4ff8d4749888b2b6f")
    await driver.manage().window().setRect(1347, 748)
    await driver.findElement(By.css(".cdk-focused .mat-icon")).click()
    await driver.executeScript("window.scrollTo(0,846)")
    await driver.executeScript("window.scrollTo(0,346)")
    {
      const element = await driver.findElement(By.css(".cdk-focused .mat-icon"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".cdk-focused .mat-icon"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".cdk-focused .mat-icon"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".cdk-focused .mat-icon")).click()
  })
})
