// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Se Connecter', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Se Connecter', async function() {
    await driver.get("http://localhost:4200/home")
    await driver.manage().window().setRect(1347, 748)
    await driver.findElement(By.css(".mt-3 > .mat-button-wrapper")).click()
    await driver.findElement(By.id("mat-input-0")).click()
    await driver.findElement(By.id("mat-input-0")).sendKeys("fred@gmail.com")
    {
      const element = await driver.findElement(By.css(".mr-1 > .mat-button-wrapper"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("mat-input-1")).sendKeys("repasser")
    await driver.findElement(By.css(".mr-1 > .mat-button-wrapper")).click()
  })
})
