// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Supprimer Un projet', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Supprimer Un projet', async function() {
    await driver.get("http://localhost:4200/login")
    await driver.manage().window().setRect(1347, 748)
    await driver.findElement(By.id("mat-input-0")).click()
    await driver.findElement(By.id("mat-input-0")).sendKeys("fred@gmail.com")
    await driver.findElement(By.id("mat-input-1")).sendKeys("repasser")
    await driver.findElement(By.id("mat-input-1")).sendKeys(Key.ENTER)
    {
      const element = await driver.findElement(By.css(".nav-menu .mat-button-wrapper"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.executeScript("window.scrollTo(0,300)")
    await driver.findElement(By.css(".mat-row:nth-child(10) #delete .mat-icon")).click()
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
    await driver.executeScript("window.scrollTo(0,300)")
  })
})
