// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Terminé un sprint', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Terminé un sprint', async function() {
    await driver.get("http://localhost:4200/login")
    await driver.manage().window().setRect(1347, 748)
    await driver.findElement(By.id("mat-input-0")).click()
    await driver.findElement(By.id("mat-input-0")).sendKeys("fred@gmail.com")
    await driver.findElement(By.css(".ng-tns-c5-1 .mat-form-field-infix")).click()
    await driver.findElement(By.id("mat-input-1")).sendKeys("repasser")
    await driver.findElement(By.id("mat-input-1")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".mat-raised-button .mat-icon")).click()
    {
      const element = await driver.findElement(By.css(".button-right"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".button-right .mat-icon")).click()
    {
      const element = await driver.findElement(By.css(".cdk-focused"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".cdk-focused")).click()
    await driver.findElement(By.css(".mat-warn > .mat-button-wrapper")).click()
    await driver.findElement(By.id("mat-input-2")).click()
    await driver.findElement(By.id("mat-input-2")).sendKeys("urlrelease")
    await driver.findElement(By.css(".cdk-focused > .mat-button-wrapper")).click()
  })
})
